-- =====================================================================
-- Notifications, one row per recipient.
--
-- Not one row per event with a list of readers: read state is personal,
-- and a shared row would need a second table to record who had seen it
-- anyway. Fanning out at write time costs a few rows and makes every
-- read a single indexed lookup.
-- =====================================================================

CREATE TABLE notifications (
  id              BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  recipient_id    UUID        NOT NULL,
  kind            TEXT        NOT NULL,
  severity        TEXT        NOT NULL,
  title           TEXT        NOT NULL,
  body            TEXT        NOT NULL,
  -- Who the notification is about: the recruiter who missed the standard,
  -- or whoever performed the action. Null when it is about nobody.
  subject_id      UUID,
  subject_name    TEXT,
  -- When the reported thing happened, which is not when the row was written:
  -- the performance check runs hours after the shift it judges.
  occurred_at     TIMESTAMPTZ NOT NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  read_at         TIMESTAMPTZ,
  reference       TEXT        NOT NULL DEFAULT '',

  -- What makes this notification the one it is. The audit id for an action,
  -- the shift date plus the person for a performance miss. The generators are
  -- allowed to run again over ground they have already covered — a restart,
  -- an overlapping schedule — and this is what stops that duplicating anybody's
  -- inbox.
  dedupe_key      TEXT        NOT NULL,

  CONSTRAINT notifications_kind_known
    CHECK (kind IN ('ACTIVITY', 'PERFORMANCE')),
  CONSTRAINT notifications_severity_known
    CHECK (severity IN ('INFO', 'WARNING', 'ALERT'))
);

CREATE UNIQUE INDEX notifications_recipient_dedupe_idx
  ON notifications (recipient_id, dedupe_key);

-- The one query the API makes: this person's newest first, optionally unread
-- only. id DESC rather than created_at DESC because ids are assigned in
-- insertion order and two rows written in the same fan-out share a timestamp.
CREATE INDEX notifications_recipient_id_idx
  ON notifications (recipient_id, id DESC);

CREATE INDEX notifications_recipient_unread_idx
  ON notifications (recipient_id, id DESC)
  WHERE read_at IS NULL;

-- =====================================================================
-- How far each generator has got.
--
-- A table rather than memory: the audit poller must not replay the whole
-- log after every restart, and the performance check must not re-judge a
-- shift it has already judged.
-- =====================================================================

CREATE TABLE sync_state (
  name       TEXT        PRIMARY KEY,
  position   TEXT        NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
